---
title: "Problem3"
author: "Devin Etcitty"
date: "4/25/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(tidyverse)
library(scales)
library(igraph)
library(plyr)
library(reshape2)
```

#### Read in undweighted10.dat
First, read in the edge list for 2010 from the undweighted10.dat file

```{r}
setwd("~/columbia/APMA4990/msd-homework/homework/homework_3/problem_3")
year2010 <- read.delim("undweighted10.dat", header = FALSE, sep = ' ')
colnames(year2010) <- c('userID1', 'userID2', 'num_email')

```


Make a plot of the distribution of edge weights for the entire network
Use a log-log scale and comment on the result. What does it tell you about the distribution of tie strength?

```{r}
count_df <- year2010 %>% 
  count('num_email')

count_df

```

# Graph

```{r}
ggplot(count_df, aes(x=num_email, y =n)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()


```


```{r}
ggplot(count_df, aes(x=n, y =num_email)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()

```


```{r}
ggplot(count_df, aes(x=num_email, y=n)) +
  geom_jitter() +
  scale_x_log10(name = "Number of Emails Sent", labels=comma) +
  scale_y_log10(name = "Number of People", labels=comma) 
```


```{r}
power2 <- 2^(0:10)
power2 <- append(power2, 0, 0)
power2
```


for(threshold in power2) {
  filter(year2010, num_email > threshold) %>%
    count() %>%
    print()
  
}

```{r}
filter(year2010, num_email > power2) %>% count()
#ddply(year2010, )


mod_func <- function(arr, df, x) {   
  arr <- filter(df, num_email > x) %>%
    count()
  return(arr)
}

ddply(power2, mod_func, df=year2010, x=power2)


year2010 %>% 
  rowwise() %>%
  mutate(var = 1)

boy <- function(df, x) {
  df %>%
  rowwise() %>%
  add_column(var = x) %>%
  #mutate(var = x)
  
  
  return(df)
}

boy(year2010, 33)

boy(year2010, power2)
ddply(year2010, boy, x=power2)
```




```{r}
po <- as.data.frame(t(power2))
po %>%
  mutate_all()

year2010 %>%
  
  mutate_all(po)

adply(power2, function(x) {})


```


```{r}
for(i in power2) {
  df <- year2010 %>%
    filter(num_email > i)
  g <- graph_from_data_frame(year2010, directed = FALSE, vertices = NULL)
  nodes <- gorder(g)
  edges <- gsize(g)
  num_connect_comps <- no.clusters(g)
  clus <- clusters(g)
  mem <- clus$membership
  
  #print(attributes(mem))
  
  #print(num_connect_comps)
  #print(g$num_email)
  #print(clus$no)
  group1 <- length(mem[mem==2])
  #print(group1)
  #print(g)
  #freq_nodes <- count(df, "num_email")
  #print(freq_nodes)
  str(g)
}


```

